# Generated by Django 3.2.13 on 2022-06-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course'),
        ('profiles', '0004_userprofile_courses_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='courses_bought',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
