# Generated by Django 3.2.13 on 2022-06-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_courses_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='courses_bought',
        ),
    ]
