# Generated by Django 3.2.13 on 2022-06-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course'),
        ('profiles', '0007_userprofile_courses_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='courses_bought',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Course'),
        ),
    ]
