# Generated by Django 3.2.13 on 2022-06-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20220607_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='courses_bought',
        ),
    ]
