# Generated by Django 3.2.13 on 2022-06-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_course_bought'),
        ('profiles', '0016_remove_userprofile_courses_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_bought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='courses.course'),
        ),
    ]
