# Generated by Django 3.2.13 on 2022-06-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20220607_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='course_brought',
            new_name='course_bought',
        ),
    ]
