# Generated by Django 3.2.13 on 2022-06-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_contact_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='newsletter',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, null=True, verbose_name='Would you like to sign up for our newsletter?'),
        ),
    ]
