# Generated by Django 3.2.13 on 2022-06-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_contact_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='newsletter',
        ),
    ]
