# Generated by Django 3.2.13 on 2022-06-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_courses_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courses_bought',
        ),
    ]
