# Generated by Django 3.2.13 on 2022-06-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_userprofile_courses_bought'),
        ('courses', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courses_bought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_bought', to='profiles.userprofile'),
        ),
    ]
