# Generated by Django 3.2.13 on 2022-06-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_courses_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courses_bought',
        ),
    ]
