# Generated by Django 3.2.13 on 2022-06-07 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_remove_course_courses_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_bought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_bought', to=settings.AUTH_USER_MODEL),
        ),
    ]
