# Generated by Django 3.2.13 on 2022-06-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_remove_userprofile_courses_bought'),
        ('courses', '0006_course_course_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_bought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_bought', to='profiles.userprofile'),
        ),
    ]
