# Generated by Django 3.2.13 on 2022-06-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_course_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_bought',
        ),
    ]
