# Generated by Django 3.2.13 on 2022-06-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_examskill_further_study'),
        ('courses', '0008_remove_course_course_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='examskill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.examskill'),
        ),
    ]
