# Generated by Django 3.2.13 on 2022-06-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20220609_0941'),
        ('courses', '0009_course_examskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='paid',
        ),
        migrations.AlterField(
            model_name='course',
            name='examskill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.examskill', verbose_name='EXAM: (Leave blank if your course is General English)'),
        ),
    ]
