# Generated by Django 3.2.13 on 2022-06-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20220609_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='examskill',
        ),
    ]
