# Generated by Django 3.2.13 on 2022-06-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_examskill'),
        ('lms', '0009_auto_20220609_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseskill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.courseskill', verbose_name='EXAM: (Leave blank if your course is General English)'),
        ),
    ]
