# Generated by Django 3.2.13 on 2022-06-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_alter_coursecategory_name'),
        ('courses', '0014_auto_20220610_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseskill',
        ),
        migrations.AddField(
            model_name='course',
            name='courseskill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.courseskill', verbose_name='EXAM: (Leave blank if your course is General English)'),
        ),
    ]
