# Generated by Django 3.2.13 on 2022-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_courseskill_category'),
        ('courses', '0016_auto_20220610_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseskill',
            field=models.ManyToManyField(blank=True, null=True, to='lms.CourseCategory', verbose_name='EXAM: (Leave blank if your course is General English)'),
        ),
    ]
