# Generated by Django 3.2.13 on 2022-06-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_rename_category_courseskill_course_category'),
        ('courses', '0018_alter_course_courseskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseskill',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='lms.CourseSkill'),
        ),
    ]
