# Generated by Django 3.2.13 on 2022-06-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_auto_20220610_1635'),
        ('courses', '0020_alter_course_courseskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseskill',
        ),
        migrations.AddField(
            model_name='course',
            name='courseskill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.courseskill'),
        ),
    ]
