# Generated by Django 3.2.13 on 2022-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_auto_20220610_1640'),
        ('courses', '0021_auto_20220610_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseskill',
        ),
        migrations.AddField(
            model_name='course',
            name='courseskill',
            field=models.ManyToManyField(blank=True, null=True, to='lms.CourseSkill'),
        ),
    ]
