# Generated by Django 3.2.13 on 2022-06-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20220610_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseskill',
        ),
    ]
