# Generated by Django 3.2.13 on 2022-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_alter_coursecategory_name'),
        ('courses', '0023_remove_course_courseskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseskill',
            field=models.ManyToManyField(blank=True, null=True, to='lms.CourseCategory'),
        ),
    ]
