# Generated by Django 3.2.13 on 2022-06-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20220612_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, choices=[('exams', 'Exam Skills'), ('general_eng', 'General English')], max_length=20, null=True),
        ),
    ]
