# Generated by Django 3.2.13 on 2022-06-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseskill',
            new_name='course_category',
        ),
    ]
