# Generated by Django 3.2.13 on 2022-06-24 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20220620_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_meta',
            field=models.CharField(blank=True, max_length=50, verbose_name="This field is for SEO purposes.  Please enter some tags to describe your course and separate each tag with a comma.  For example, 'IELTS, English, Exam'"),
        ),
        migrations.AlterField(
            model_name='course',
            name='card_description',
            field=models.TextField(null=True, verbose_name="What is a brief description of your course?  This will appear in the shop's search results."),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category', verbose_name='What is category of your lesson? It can beGeneral English or Exam Skills.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True, verbose_name="What is a detailed description of your course?  This will appear on the course's dedicated page, so be as detailed as you like."),
        ),
    ]
