# Generated by Django 3.2.13 on 2022-06-15 08:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0032_alter_lessoncategory_name'),
        ('courses', '0032_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='card_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="What is a brief description of your course/  This will appear in the shop's search results."),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category', verbose_name='What is category of your lesson?  It can be General English or Exam Skills.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lessoncategory', verbose_name='Now choose what lessons are included in this course.  This step is very important!'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="What is a detailed description of your course?  This will appear on the course's dedicated page, so be as detailed as you like."),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=254, verbose_name='What is the name of your course?'),
        ),
    ]
