# Generated by Django 3.2.13 on 2022-06-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_auto_20220624_1203'),
        ('courses', '0034_course_course_meta'),
    ]

    operations = [
    ]
