# Generated by Django 3.2.13 on 2022-06-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_merge_0032_auto_20220624_1203_0034_course_course_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_meta',
        ),
    ]
