# Generated by Django 3.2.13 on 2022-06-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_remove_course_course_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_meta',
            field=models.CharField(blank=True, max_length=50, verbose_name="This field is for SEO purposes.  Please enter some tags to describe your course and separate each tag with a comma.  For example, 'IELTS, English, Exam'"),
        ),
    ]
