# Generated by Django 3.2.13 on 2022-06-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_course_course_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=254, verbose_name='What is the name of your course?THIS MUST BE THE SAME AS THE LESSON CATEGORY!'),
        ),
    ]
