# Generated by Django 3.2.13 on 2022-06-08 07:17

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_examskill_question_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examskill',
            name='question_approach',
            field=models.TextField(verbose_name='Section 3 - Question Approach'),
        ),
        migrations.AlterField(
            model_name='examskill',
            name='sample_question_questions',
            field=models.TextField(verbose_name='Section 2 - Sample Questions'),
        ),
        migrations.AlterField(
            model_name='examskill',
            name='sample_question_text',
            field=models.TextField(verbose_name='Section 2 - Sample Reading Passage'),
        ),
        migrations.AlterField(
            model_name='examskill',
            name='upload_answers',
            field=models.FileField(blank=True, upload_to='', verbose_name='Section 4 - Further Practice Questions (Answers)'),
        ),
        migrations.AlterField(
            model_name='examskill',
            name='upload_questions',
            field=models.FileField(blank=True, upload_to='', verbose_name='Section 4 - Further Practice Questions (PDF)'),
        ),
        migrations.AlterField(
            model_name='examskill',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Section 3 - Video'),
        ),
    ]
