# Generated by Django 3.2.13 on 2022-06-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_examskill_sample_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='examskill',
            name='further_study',
            field=models.TextField(default=1, verbose_name='Section 4 - Further Study Information'),
            preserve_default=False,
        ),
    ]
