# Generated by Django 3.2.13 on 2022-06-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20220609_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examskill',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='examskill',
            old_name='exam_name',
            new_name='name',
        ),
    ]
