# Generated by Django 3.2.13 on 2022-06-09 12:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_examskill'),
        ('lms', '0008_auto_20220609_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KET', 'KET'), ('PET', 'PET'), ('FCE', 'FCE'), ('CAE', 'CAE'), ('CPE', 'CPE'), ('IELTS', 'IELTS'), ('GEN - A1', 'GEN - A1'), ('GEN - A2', 'GEN - A2'), ('GEN - B1', 'GEN - B1'), ('GEN - B2', 'GEN - B2'), ('GEN - C1', 'GEN - C1'), ('GEN - C2', 'GEN - C2')], max_length=50)),
                ('exam_section', models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Writing', 'Writing'), ('Speaking', 'Speaking'), ('Listening', 'Listening')], max_length=20)),
                ('question_type', models.CharField(max_length=100)),
                ('question_image', models.ImageField(choices=[('/reading.jpg', 'Reading'), ('/writing.jpg', 'Writing'), ('/listening.jpg', 'Listening'), ('/speaking.jpg', 'Speaking')], default='Reading', upload_to='')),
                ('question_overview', models.TextField(verbose_name='Section 1 - Question Overview')),
                ('sample_question_text', models.TextField(blank=True, verbose_name='Section 2 - Sample Passage (can be left blank)')),
                ('sample_question_questions', models.TextField(verbose_name='Section 2 - Sample Questions')),
                ('question_approach', models.TextField(verbose_name='Section 3 - Question Approach')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, verbose_name='Section 3 - Video')),
                ('further_study', models.TextField(verbose_name='Section 4 - Further Study Information')),
                ('upload_questions', models.FileField(blank=True, upload_to='', verbose_name='Section 4 - Further Practice Questions (PDF)')),
                ('upload_answers', models.FileField(blank=True, upload_to='', verbose_name='Section 4 - Further Practice Questions (Answers)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ExamCategory',
        ),
        migrations.DeleteModel(
            name='ExamSkill',
        ),
    ]
