# Generated by Django 3.2.13 on 2022-06-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_auto_20220609_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KET', 'KET'), ('PET', 'PET'), ('FCE', 'FCE'), ('CAE', 'CAE'), ('CPE', 'CPE'), ('IELTS', 'IELTS'), ('GEN - A1', 'GEN - A1'), ('GEN - A2', 'GEN - A2'), ('GEN - B1', 'GEN - B1'), ('GEN - B2', 'GEN - B2'), ('GEN - C1', 'GEN - C1'), ('GEN - C2', 'GEN - C2')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
            },
        ),
        migrations.AlterField(
            model_name='courseskill',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.coursecategory'),
        ),
    ]
