# Generated by Django 3.2.13 on 2022-06-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_auto_20220609_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
