# Generated by Django 3.2.13 on 2022-06-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_coursecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseskill',
            name='course_full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
