# Generated by Django 3.2.13 on 2022-06-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_coursecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseskill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.coursecategory'),
        ),
        migrations.AlterField(
            model_name='courseskill',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
