# Generated by Django 3.2.13 on 2022-06-10 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_auto_20220609_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseskill',
            name='course_num',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
