# Generated by Django 3.2.13 on 2022-06-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_courseskill_course_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseskill',
            name='course_full_name',
        ),
        migrations.AddField(
            model_name='courseskill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.coursecategory'),
        ),
        migrations.AlterField(
            model_name='courseskill',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
