# Generated by Django 3.2.13 on 2022-06-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_courseskill_course_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(choices=[('KET', 'KET'), ('PET', 'PET'), ('FCE', 'FCE'), ('CAE', 'CAE'), ('CPE', 'CPE'), ('IELTS', 'IELTS'), ('GEN - A1', 'GEN - A1'), ('GEN - A2', 'GEN - A2'), ('GEN - B1', 'GEN - B1'), ('GEN - B2', 'GEN - B2'), ('GEN - C1', 'GEN - C1'), ('GEN - C2', 'GEN - C2')], max_length=100),
        ),
    ]
