# Generated by Django 3.2.13 on 2022-06-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_auto_20220610_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
