# Generated by Django 3.2.13 on 2022-06-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_alter_coursecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseskill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.coursecategory'),
        ),
    ]
