# Generated by Django 3.2.13 on 2022-06-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_alter_courseskill_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseskill',
            old_name='category',
            new_name='course_category',
        ),
    ]
