# Generated by Django 3.2.13 on 2022-06-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_rename_category_courseskill_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseskill',
            old_name='course_category',
            new_name='category',
        ),
    ]
