# Generated by Django 3.2.13 on 2022-06-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_rename_course_category_courseskill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseskill',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.coursecategory'),
        ),
    ]
