# Generated by Django 3.2.13 on 2022-06-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_auto_20220610_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseskill',
            name='category',
        ),
        migrations.AddField(
            model_name='courseskill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.coursecategory'),
        ),
    ]
