# Generated by Django 3.2.13 on 2022-06-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_alter_coursecategory_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSkill',
            new_name='Lessons',
        ),
    ]
