# Generated by Django 3.2.13 on 2022-06-13 16:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_auto_20220612_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='question_approach',
            field=ckeditor.fields.RichTextField(verbose_name='Section 3 - Question Approach'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='question_overview',
            field=ckeditor.fields.RichTextField(verbose_name='Section 1 - Question Overview'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='sample_question_questions',
            field=ckeditor.fields.RichTextField(verbose_name='Section 2 - Sample Questions'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='sample_question_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Section 2 - Sample Passage (can be left blank)'),
        ),
    ]
