# Generated by Django 3.2.13 on 2022-06-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_auto_20220612_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='What is the name of the new category?'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lessoncategory', verbose_name='Choose a category for this lesson.  If it is a new category, not in the list, you will need to create a category in the previous section first:'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='exam_section',
            field=models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Writing', 'Writing'), ('Speaking', 'Speaking'), ('Listening', 'Listening')], max_length=20, verbose_name='If this lesson is for an exam, which section is it for?  Otherwise you can leave this blank.'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='question_image',
            field=models.CharField(choices=[('https://res.cloudinary.com/corderoybear/image/upload/v1655371458/static/media/reading.9b0786861128.jpg', 'Reading'), ('https://res.cloudinary.com/corderoybear/image/upload/v1655371458/static/media/writing.23e6ff8e3f48.jpg', 'Writing'), ('https://res.cloudinary.com/corderoybear/image/upload/v1655371457/static/media/listening.a10f4492e111.jpg', 'Listening'), ('https://res.cloudinary.com/corderoybear/image/upload/v1655371459/static/media/speaking.8e29b8f0faba.jpg', 'Speaking')], default='Reading', max_length=200, verbose_name='What skill does the lesson relate to (for the thumbnail image)?'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='question_overview',
            field=models.TextField(verbose_name='Section 2 - What kind of question is it?'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='question_type',
            field=models.CharField(max_length=100, verbose_name='What kind of question is it?  Is it grammar, vocabulary or a specific exam question?'),
        ),
    ]
