# Generated by Django 3.2.13 on 2022-06-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_auto_20220620_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='What is the name of the new category? (For example, IELTS, FCE, General English?) MUST BE UNIQUE and have NO PUNCTUATION'),
        ),
    ]
