# Generated by Django 3.2.13 on 2022-06-13 16:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_auto_20220613_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='further_study',
            field=ckeditor.fields.RichTextField(verbose_name='Section 4 - Further Study Information'),
        ),
    ]
