# Generated by Django 3.2.13 on 2022-06-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0028_alter_lessoncategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='category',
            field=models.ForeignKey(default='IELTS', on_delete=django.db.models.deletion.CASCADE, to='lms.lessoncategory', verbose_name='Choose a category for this lesson.  If it is a new category, not in the list, you will need to create a category in the previous section first:'),
        ),
    ]
