# Generated by Django 3.2.13 on 2022-06-15 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_alter_lessons_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.lessoncategory', verbose_name='Choose a category for this lesson.  If it is a new category, not in the list, you will need to create a category in the previous section first:'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='exam_section',
            field=models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Writing', 'Writing'), ('Speaking', 'Speaking'), ('Listening', 'Listening')], max_length=20, verbose_name='If this lesson is for an exam, which section is it for?  Otherwise you can leave this blank.'),
        ),
    ]
