# Generated by Django 3.2.13 on 2022-06-21 08:49

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0030_alter_lessons_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='course_num',
        ),
        migrations.AlterField(
            model_name='lessons',
            name='upload_answers',
            field=models.FileField(blank=True, upload_to='', verbose_name='Section 4 - Further Practice Questions (Answers) (can be left blank)'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='upload_questions',
            field=models.FileField(blank=True, upload_to='', verbose_name='Section 4 - Further Practice Questions (PDF) (can be left blank)'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Section 3 - Video (can be left blank)'),
        ),
    ]
