# Generated by Django 3.2.13 on 2022-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0030_auto_20220615_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='question_image',
            field=models.ImageField(choices=[('/reading.jpg', 'Reading'), ('/writing.jpg', 'Writing'), ('/listening.jpg', 'Listening'), ('/speaking.jpg', 'Speaking')], default='Reading', upload_to='', verbose_name='What skill does the lesson relate to?'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='question_type',
            field=models.CharField(max_length=100, verbose_name='What kind of question is it?  Is it grammar, vocabulary or a specific exam question?'),
        ),
    ]
