# Generated by Django 3.2.13 on 2022-06-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0031_auto_20220615_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='What is the name of the new category?'),
        ),
    ]
