# Generated by Django 3.2.13 on 2022-06-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_alter_lessons_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='question_image',
            field=models.ImageField(choices=[('thumbnails/reading.jpg', 'Reading'), ('thumbnails/writing.jpg', 'Writing'), ('thumbnails/listening.jpg', 'Listening'), ('thumbnails/speaking.jpg', 'Speaking')], default='Reading', upload_to='', verbose_name='What skill does the lesson relate to?'),
        ),
    ]
