# Generated by Django 3.2.13 on 2022-06-17 10:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0046_alter_lessons_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='question_image',
            field=cloudinary.models.CloudinaryField(choices=[('/reading.jpg', 'Reading'), ('/writing.jpg', 'Writing'), ('/listening.jpg', 'Listening'), ('/speaking.jpg', 'Speaking')], default='Reading', max_length=255, verbose_name='What skill does the lesson relate to?'),
        ),
    ]
