# Generated by Django 3.2.13 on 2022-06-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0047_alter_lessons_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='question_image',
            field=models.ImageField(choices=[('media/lms_thumbnails/reading.jpg', 'Reading'), ('/writing.jpg', 'Writing'), ('/listening.jpg', 'Listening'), ('/speaking.jpg', 'Speaking')], default='Reading', upload_to='', verbose_name='What skill does the lesson relate to?'),
        ),
    ]
