# Generated by Django 3.2.13 on 2022-06-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0056_alter_lessons_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='question_image',
            field=models.CharField(choices=[('1', 'Reading'), ('2', 'Writing'), ('3', 'Listening'), ('https://res.cloudinary.com/corderoybear/image/upload/v1655371459/static/media/speaking.8e29b8f0faba.jpg', 'Speaking')], default='Reading', max_length=200, verbose_name='What skill does the lesson relate to?'),
        ),
    ]
