# Generated by Django 3.2.13 on 2022-06-19 13:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0059_alter_lessons_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='question_overview',
            field=tinymce.models.HTMLField(verbose_name='Section 1 - Question Overview'),
        ),
    ]
