# Generated by Django 3.2.13 on 2022-06-19 13:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0061_alter_lessons_question_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='question_overview',
            field=tinymce.models.HTMLField(),
        ),
    ]
