# Generated by Django 3.2.13 on 2022-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0062_alter_lessons_question_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='question_overview',
            field=models.TextField(),
        ),
    ]
