# Generated by Django 3.2.13 on 2022-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0063_alter_lessons_question_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='further_study',
            field=models.TextField(verbose_name='Section 4 - Further Study Information'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='question_approach',
            field=models.TextField(verbose_name='Section 3 - Question Approach'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='sample_question_questions',
            field=models.TextField(verbose_name='Section 2 - Sample Questions'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='sample_question_text',
            field=models.TextField(blank=True, verbose_name='Section 2 - Sample Passage (can be left blank)'),
        ),
    ]
