# Generated by Django 3.2.13 on 2022-06-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0064_auto_20220619_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='question_overview',
            field=models.TextField(verbose_name='Section 2 - What kind of question is it?'),
        ),
    ]
